# Copyright (c) 2026 Wind River Systems, Inc.

BB_CONF_FRAGMENT_SUMMARY = "This fragment allows commercial licenses"
BB_CONF_FRAGMENT_DESCRIPTION = "Allow commercial licenses \
  - Needed by meta-raspberrypi for the Raspberry Pi firmware and synpatics driver \
"

# Set the accepted license flags to allow the use of commercial graphics drivers.
LICENSE_FLAGS_ACCEPTED += "commercial synaptics-killswitch"
