# Copyright (c) 2026 Wind River Systems, Inc.

# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "oeros"
BBFILE_PATTERN_oeros = "^${LAYERDIR}/"
BBFILE_PRIORITY_oeros = "5"

LAYERSERIES_COMPAT_oeros = "wrynose"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_oeros = "3"

LAYERDEPENDS_oeros = "core openembedded-layer meta-python virtualization-layer"
