# Copyright (c) 2026 Wind River Systems, Inc.

# OpenEmbedded ROS (OE ROS) Reference Distribution
DISTRO = "oeros"
DISTRO_NAME = "Oeros (OpenEmbedded ROS Reference Distro)"
DISTRO_VERSION = "2026.04"
DISTRO_CODENAME = "alpha"

MAINTAINER = "Rob Woolley <rob.woolley@windriver.com>"

DISTRO_FEATURES ?= "${DISTRO_FEATURES_DEFAULT} ${OEROS_DEFAULT_DISTRO_FEATURES}"

DISTRO_FEATURES:append = " virtualization"
DISTRO_FEATURES:append = " wayland opengl vulkan polkit"
DISTRO_FEATURES:append = " opencl"
DISTRO_FEATURES:append = " pam"

DISTRO_EXTRA_RDEPENDS += "${OEROS_DEFAULT_EXTRA_RDEPENDS}"
DISTRO_EXTRA_RRECOMMENDS += "${OEROS_DEFAULT_EXTRA_RRECOMMENDS}"

include ${LAYERDIR}/conf/distro/include/packageconfig.inc
include ${LAYERDIR}/conf/distro/include/zenoh.inc
